<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/default.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['link_to_not_existing_file'] = "Het bestand \"%s\" staat niet op uw server!";
$GLOBALS['TL_LANG']['ERR']['uploadError'] = "Het bestand \"%s\" kon niet worden geüpload!";
$GLOBALS['TL_LANG']['ERR']['fileDontExist'] = "Het bestand \"%s\" bestaat niet!";
$GLOBALS['TL_LANG']['ERR']['fileNotReadable'] = "Het bestand \"%s\" is niet leesbaar! Controleer uw toegangsrechten.";
$GLOBALS['TL_LANG']['ERR']['dirNotWriteable'] = "De map \"%s\" is niet beschrijfbaar! Controleer de chmod instellingen!";
$GLOBALS['TL_LANG']['gallery_creator']['back_to_general_view'] = "Terug naar het algemene scherm";
$GLOBALS['TL_LANG']['gallery_creator']['subalbums'] = "subalbums";
$GLOBALS['TL_LANG']['gallery_creator']['pictures'] = "afbeeldingen";
$GLOBALS['TL_LANG']['gallery_creator']['contains'] = "bevat";
$GLOBALS['TL_LANG']['gallery_creator']['fe_authentification_error']['0'] = "Authentification error";
$GLOBALS['TL_LANG']['gallery_creator']['fe_authentification_error']['1'] = "U probeerde een beschermd album binnen te gaan. Log-in als frontend gebruiker of check uw rechten.";
 
?>
