<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/modules.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['1'] = "Maak en verander albums/galerijen.";
$GLOBALS['TL_LANG']['FMD']['gallery_creator_fmd']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['FMD']['gallery_creator_fmd']['1'] = "Toon Gallery Creator albums als frontend module.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['1'] = "Toon Gallery Creator albums als frontend inhoudselement.";
 
?>