<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/tl_content.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['miscellaneous_legend'] = "Diverse instellingen";
$GLOBALS['TL_LANG']['tl_content']['picture_sorting_legend'] = "Sorteer opties";
$GLOBALS['TL_LANG']['tl_content']['thumb_legend'] = "Thumbnail instellingen";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['0'] = "Thumbnails per rij";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['1'] = "Kies het aantal thumbnails per rij (0=zoveel als mogelijk).";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['0'] = "Publiceer deze albums";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['1'] = "Geselecteerde albums worden weergegeven in het frontend.";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['0'] = "Galerij template";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['1'] = "Kies een eigen galerij template";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['0'] = "Activeer Ajax-Thumb-Slider";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['1'] = "Activeer Ajax-Thumb-Slider op mouseover in de albumlijst?";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['0'] = "Omleiden in het geval van een enkel album";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['1'] = "De bezoeker wordt automatisch omgeleid naar de detailweergave als er slechts één album is.";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['0'] = "Onderdelen per pagina in de albumlijst";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['1'] = "Aantal onderdelen op een pagina in de albumlijst (0=alles weergeven/geen paginering).";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['0'] = "Thumbnails per pagina";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['1'] = "Aantal thumbnails per pagina in de detailweergave (0=alles weergeven/geen paginering). ";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['0'] = "Sorteren";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['1'] = "Volgens welk veld moet de galerij gesorteerd worden?";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['0'] = "Sorteervolgorde";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['1'] = "DESC: aflopend (descending), ASC: oplopend (ascending)";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['0'] = "Detailweergave: thumbnail breedte en hoogte";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['1'] = "Geef hier de thumbnail maten en de resize mode.";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['0'] = "Albumlijst: thumbnail breedte en hoogte";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['1'] = "Geef hier de thumbnail maten en de resize mode.";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['0'] = "Ware grootte/nieuw venster";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['1'] = "Open de afbeelding op ware grootte in een lightbox of de link in een nieuw browser venster.";
 
?>
