<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/tl_gallery_creator_pictures.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['id']['0'] = "Afbeelding ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['published']['0'] = "Publiceer afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['date']['0'] = "Aanmaakdatum";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['owner']['0'] = "Eigenaar afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['name']['0'] = "Bestandsnaam";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['addCustomThumb']['0'] = "Custom thumbnail";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['customThumb']['0'] = "Voeg een custom thumnail toe.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['title']['0'] = "Titel afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['comment']['0'] = "Bijschrift afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['sorting']['0'] = "Sorteervolgorde";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['filename']['0'] = "Bestandsnaam";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['path']['0'] = "Path";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['0'] = "Bewerk afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['1'] = "Bewerk afbeelding ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['0'] = "Wis afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['1'] = "Wis afbeelding ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['0'] = "Verander volgorde";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['1'] = "Verplaats afbeelding ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['0'] = "Plak onder";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['1'] = "Plak onder afbeelding ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['0'] = "Roteer afbeelding";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['1'] = "Roteer afbeelding 90°.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['jumpLoader']['0'] = "Upload afbeeldingen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['jumpLoader']['1'] = "Upload afbeeldingen";
