<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/tl_gallery_creator_albums.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['album_info'] = "Album informatie";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['protection'] = "Bescherm album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_settings'] = "Beeldinstellingen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['uploader'] = "Java-uploader";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['id']['0'] = "Album ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['alias']['0'] = "Album alias";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['alias']['1'] = "De album alias wordt gebruikt i.p.v. het album ID.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['published']['0'] = "Publiceer album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['date']['0'] = "Aanmaakdatum";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['owner']['0'] = "Eigenaar album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['name']['0'] = "Naam album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['owners_name']['0'] = "Eigenaar album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['comment']['0'] = "Opmerkingen album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['thumb']['0'] = "Preview thumbnail";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['thumb']['1'] = "De thumbnail die in de album preview wordt weergegeven.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['protected']['0'] = "Bescherm album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['groups']['0'] = "Toon dit album alleen aan bepaalde gebruikersgroepen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_resolution']['0'] = "Afbeeldingsbreedte";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_resolution']['1'] = "Tijdens het uploaden wordt de afbeelding geschaald naar deze waarde.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_quality']['0'] = "Beeldkwaliteit/compressie";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_quality']['1'] = "Tijdens het uploaden wordt de afbeelding gecomprimeerd (100=beste kwaliteit/laagste compressie).";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['preserve_filename']['0'] = "Behoud de bestandsnaam";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['preserve_filename']['1'] = "Anders wordt de bestandsnaam automatisch gegenereerd.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['new']['0'] = "Nieuw album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['new']['1'] = "Maak een nieuw album.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['edit']['0'] = "Bewerk album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['edit']['1'] = "Bewerk album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['delete']['0'] = "Wis album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['delete']['1'] = "Wis album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_images']['0'] = "Upload bestanden";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_images']['1'] = "Upload afbeeldingen naar album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['import_images']['0'] = "Kopieer afbeeldingen vanuit een map op de server";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['import_images']['1'] = "Kopieer afbeeldingen vanuit een map op de server naar album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['cut']['0'] = "Verplaats album";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['cut']['1'] = "Verplaats album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteafter']['0'] = "Plak achter";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteafter']['1'] = "Plak achter album ID %s.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteinto']['0'] = "Plak in";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteinto']['1'] = "Plak in album ID %s.";
