<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/tl_module.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['thumb_legend'] = "Thumbnail instellingen";
$GLOBALS['TL_LANG']['tl_module']['image_legend'] = "Overige instellingen";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['0'] = "Galerij template";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['1'] = "Kies een galerij template";
$GLOBALS['TL_LANG']['tl_module']['gc_activateThumbSlider']['0'] = "Activeer Ajax Thumb Slider";
$GLOBALS['TL_LANG']['tl_module']['gc_activateThumbSlider']['1'] = "Activeer Ajax-Thumb-Slider op mouseover in de albumlijst?";
$GLOBALS['TL_LANG']['tl_module']['gc_AlbumsPerPage']['0'] = "Onderdelen per pagina in de albumlijst";
$GLOBALS['TL_LANG']['tl_module']['gc_AlbumsPerPage']['1'] = "Aantal onderdelen op een pagina in de albumlijst (0=alles weergeven/geen paginering).";
$GLOBALS['TL_LANG']['tl_module']['gc_ThumbsPerPage']['0'] = "Thumbnails per pagina in detailweergave";
$GLOBALS['TL_LANG']['tl_module']['gc_ThumbsPerPage']['1'] = "Aantal thumbnails per pagina in de detailweergave (0=alles weergeven/geen paginering). ";
$GLOBALS['TL_LANG']['tl_module']['gc_hierarchicalOutput']['0'] = "Hiërarchische albums frontend";
$GLOBALS['TL_LANG']['tl_module']['gc_hierarchicalOutput']['1'] = "Hiërarchische weergave albums/subalbums in het frontend.";
$GLOBALS['TL_LANG']['tl_module']['gc_size_detailview']['0'] = "Detailweergave: thumbnail breedte en hoogte";
$GLOBALS['TL_LANG']['tl_module']['gc_size_detailview']['1'] = "Geef hier de thumbnail maten en de resize mode.";
$GLOBALS['TL_LANG']['tl_module']['gc_size_albumlisting']['0'] = "Albumlijst: thumbnail breedte en hoogte";
$GLOBALS['TL_LANG']['tl_module']['gc_size_albumlisting']['1'] = "Geef hier de thumbnail maten en de resize mode.";
$GLOBALS['TL_LANG']['tl_module']['gc_fullsize']['0'] = "Ware grootte/nieuw venster";
$GLOBALS['TL_LANG']['tl_module']['gc_fullsize']['1'] = "Open de afbeelding op ware grootte in een lightbox of de link in een nieuw browser venster.";
