<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/nl/tl_settings.php 
 * 
 * Contao extension: gallery_creator 4.0.1 stable 
 * Niederländisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['gallery_creator_legend'] = "Gallery Creator instellingen";
$GLOBALS['TL_LANG']['tl_settings']['gc_disable_backend_edit_protection']['0'] = "Verwijder bescherming backend album";
$GLOBALS['TL_LANG']['tl_settings']['gc_disable_backend_edit_protection']['1'] = "Maakt het mogelijk dat alle backend gebruikers dit album bewerken, niet alleen de eigenaar van het album.";
$GLOBALS['TL_LANG']['tl_settings']['gc_album_import_copy_files']['0'] = "Kopieën van geïmporteerde bestanden";
$GLOBALS['TL_LANG']['tl_settings']['gc_album_import_copy_files']['1'] = "Het systeem maakt een kopie van elk geïmporteerde bestand.";
