<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/it/default.php 
 * 
 * Contao extension: gallery_creator 4.8.0-alpha1 
 * Italienisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['link_to_not_existing_file'] = "Il file \"%s\" non è presente nel tuo server!";
$GLOBALS['TL_LANG']['ERR']['uploadError'] = "Il file \"%s\" non può essere caricato!";
$GLOBALS['TL_LANG']['ERR']['fileDontExist'] = "Il file \"%s\" non esiste!";
$GLOBALS['TL_LANG']['ERR']['fileNotReadable'] = "Il file \"%s\" non può essere letto! Controllare i permessi.";
$GLOBALS['TL_LANG']['ERR']['dirNotWriteable'] = "La directory \"%s\" non ha i permessi di scritura! Controllare i settaggi chmod!";
$GLOBALS['TL_LANG']['gallery_creator']['back_to_general_view'] = "torna alla back to general view";
$GLOBALS['TL_LANG']['gallery_creator']['subalbums'] = "sotto album";
$GLOBALS['TL_LANG']['gallery_creator']['pictures'] = "immagini";
$GLOBALS['TL_LANG']['gallery_creator']['contains'] = "contiene";
$GLOBALS['TL_LANG']['gallery_creator']['fe_authentification_error']['0'] = "Errore di autenticazione";
$GLOBALS['TL_LANG']['gallery_creator']['fe_authentification_error']['1'] = "Hai cercato di accedere a un album protetto. Prego effettua il login come utente frontend o controlla i tuoi permessi.";
 
?>
