<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/it/tl_content.php 
 * 
 * Contao extension: gallery_creator 4.8.0-alpha1 
 * Italienisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['miscellaneous_legend'] = "Altri settaggi";
$GLOBALS['TL_LANG']['tl_content']['sorting_legend'] = "Opzioni di ordinamento lista album";
$GLOBALS['TL_LANG']['tl_content']['picture_sorting_legend'] = "Opzioni di ordinamento immagini";
$GLOBALS['TL_LANG']['tl_content']['thumb_legend'] = "Impostazioni miniature";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['0'] = "Miniature per riga";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['1'] = "Seleziona il numero di miniature per riga.(0=Quante più possibili)";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['0'] = "Pubblica questi album";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['1'] = "L'album selezionato verrà mostrato nel frontend.";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['0'] = "Template galleria";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['1'] = "Seleziona un template gallery personale.";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['0'] = "Attivare Ajax-Thumb-Slider";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['1'] = "Activare Ajax-Thumb-Slider al mouseover nella lista album?";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['0'] = "Redirezione in caso di album singolo";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['1'] = "Dev'essere reindirizzato automaticamente alla vista-dettaglio in caso di album singolo?";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['0'] = "Elementi per pagina nella lista album";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['1'] = "Numero di elementi per pagina nella lista album. Imposta a 0 per disabilitare la paginazione.";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['0'] = "Miniature per pagina nella vista dettaglio";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['1'] = "Numero di miniature per pagina nella vista dettaglio. Imposta a 0 per disabilitare la paginazione.";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['0'] = "Ordinamento album";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['1'] = "In base a quale campo dev'essere ordinato l'album?";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['0'] = "Ordinamento";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['1'] = "DESC: decrescente, ASC: crescente";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['0'] = "Ordinamento immagini";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['1'] = "In base a quale campo devono essere ordinate le immagini di un album?";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['0'] = "Ordinamento";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['1'] = "DESC: decrescente, ASC: crescente";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['0'] = "Vista dettaglio: larghezza e altezza miniatura";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['1'] = "Qui puoi impostare le dimensioni dell'immagine e la modalità di ridimensionamento.";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['1'] = "Qui puoi impostare le dimensioni dell'immagine e la modalità di ridimensionamento.";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['0'] = "Visione a dimensione intera / in una nuova finestra";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['1'] = "Apri l'immagine a dimensione intera in una lightbox oppure il link in una nuova finestra del browser";
 
?>
