<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/it/tl_gallery_creator_pictures.php 
 * 
 * Contao extension: gallery_creator 4.8.0-alpha1 
 * Italienisch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['id']['0'] = "ID immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['published']['0'] = "Pubblica l'immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['date']['0'] = "Data di creazione";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['owner']['0'] = "Proprietario immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['name']['0'] = "Nome del file";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['addCustomThumb']['0'] = "Aggiungi una miniatura personalizzata";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['customThumb']['0'] = "Miniatura personalizzata";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['title']['0'] = "Titolo immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['comment']['0'] = "Commento immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['sorting']['0'] = "Sequenza di ordinamento";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['filename']['0'] = "Nome del file";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['path']['0'] = "Percorso";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cssID']['0'] = "ID / classe CSS";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cssID']['1'] = "Qui puoi impostare un ID e una o più classi per questa immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['0'] = "Modifica le impostazioni dell'immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['1'] = "Modifica le impostazioni dell'immagine con ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['0'] = "Cancella l'immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['1'] = "Cancella l'immagine con ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['0'] = "Cambia ordinamento";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['1'] = "Sposta l'immagine con ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['0'] = "Copia sotto";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['1'] = "Copia sotto l'immagine con ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['0'] = "Ruota l'immagine";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['1'] = "Ruota l'immagine di 90°";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['jumpLoader']['0'] = "Carica immagini";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['jumpLoader']['1'] = "Carica immagini";
 
?>
