<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/it/tl_module.php 
 * 
 * Contao extension: gallery_creator 4.8.0-alpha1 
 * Italienisch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['thumb_legend'] = "Impostazioni miniatura";
$GLOBALS['TL_LANG']['tl_module']['image_legend'] = "Impostazioni varie";
$GLOBALS['TL_LANG']['tl_module']['gc_rows']['0'] = "Miniature per riga";
$GLOBALS['TL_LANG']['tl_module']['gc_rows']['1'] = "Seleziona il numero di miniature per riga.(0=Quante più possibili)";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['0'] = "Template gallery";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['1'] = "Seleziona un template gallery personalizzato";
 
?>
