<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/modules.php 
 * 
 * Contao extension: gallery_creator 5.0.0 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['0'] = "Gallery Creator";
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['1'] = "Bildgalerien erstellen und bearbeiten.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_elements'] = "Gallery Creator";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['0'] = "Gallery-Creator-Inhaltselement";
$GLOBALS['TL_LANG']['CTE']['gallery_creator']['1'] = "Gallery-Creator-Album als Inhaltselement einbinden.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce_news']['0'] = "Gallery-Creator-News-Inhaltselement";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce_news']['1'] = "Ein Gallery-Creator-Album als Inhaltselement einbinden.";
 
