<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_content.php 
 * 
 * Contao extension: gallery_creator 5.0.0 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['pagination_legend'] = "Pagination Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['miscellaneous_legend'] = "Allgemeine Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['album_listing_legend'] = "Einstellungen für die Albenauflistung";
$GLOBALS['TL_LANG']['tl_content']['picture_listing_legend'] = "Einstellungen für die Bildauflistung (Detailansicht)";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['0'] = "Vorschaubilder pro Reihe";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['1'] = "Wählen Sie die Anzahl Vorschaubilder pro Reihe aus. (0=So viele wie möglich)";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['0'] = "Lediglich folgende Alben im Frontend anzeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['1'] = "Ausgewählte Alben werden im Frontend angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_single_album']['0'] = "Album auswählen";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_single_album']['1'] = "Das ausgewählte Album wird im Frontend angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_all_albums']['0'] = "Alle angelegten Alben im Frontend zeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_hierarchicalOutput']['0'] = "Alben im Frontend hierarchisch anzeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_hierarchicalOutput']['1'] = "Alben im Frontend hierarchisch anzeigen (Alben und Unteralben)";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['0'] = "Galerietemplate";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['1'] = "Hier können Sie das Galerietemplate auswählen.";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['0'] = "Ajax-Thumb-Slider aktivieren";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['1'] = "Ajax-Thumb-Slider bei mouseover in der Albenübersicht aktivieren?";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['0'] = "Weiterleitung bei einzelnem Album";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['1'] = "Soll, wenn nur ein Album ausgewählt wurde, automatisch zur Detailansicht weitergeleitet weden?";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['0'] = "Anzahl Alben pro Seite in der Albenübersicht";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['1'] = "Die Anzahl an Alben pro Seite in der Albenübersicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['0'] = "Anzahl Bilder pro Seite in der Detailansicht";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['1'] = "Anzahl Bilder pro Seite in der Detailansicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_PaginationNumberOfLinks']['0'] = "Anzahl Links in der Pagination Navigation";
$GLOBALS['TL_LANG']['tl_content']['gc_PaginationNumberOfLinks']['1'] = "Legen Sie die Anzahl Links in der Pagination Navigation fest. Standardwert ist 7.";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['0'] = "Sortierung der Alben";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['1'] = "Nach welchem Feld sollen die Alben im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['0'] = "Sortierung der Bilder";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['1'] = "Nach welchem Feld sollen die Bilder in einem einzelnen Album im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['0'] = "Detailansicht: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['0'] = "Detailansicht: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['0'] = "Albumauflistung: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['0'] = "Albumauflistung: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['0'] = "Großansicht/Neues Fenster";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['1'] = "Großansicht des Bildes in einer Lightbox bzw. den Link in einem neuem Browserfenster öffnen.";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingDirection']['DESC'] = "Absteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingDirection']['ASC'] = "Aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['sorting'] = "Backend-Modul Reihenfolge (sorting)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['id'] = "ID";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['date'] = "Erstellungsdatum (date)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['name'] = "Name (name)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['owner'] = "Albumbesitzer (owner)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['comment'] = "Beschreibungstext (comment)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['title'] = "Bildtitel (title)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['tstamp'] = "&Auml;nderungsdatum (tstamp)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['alias'] = "Albumalias (alias)";
$GLOBALS['TL_LANG']['tl_content']['gc_sortingField']['visitors'] = "Besucherzahl (visitors)";

?>
