<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_gallery_creator_pictures.php
 *
 * Contao extension: gallery_creator 5.0.0
 * Deutsch translation file
 *
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Marko Cupic (markocupic)
 * Translator: Marko Cupic (markocupic)
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['media_integration'] = "Video- oder Soundintegration";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['expert_legend'] = "Experten-Einstellungen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['id']['0'] = "Bild-ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['pid']['0'] = "Album-ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['pid']['1'] = "Das Ändern der Album-ID kann die Konsistenz der Daten gefährden!";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['fileID']['0'] = "Dateisystem-ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['image_info']['0'] = "Bildinformationen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['published']['0'] = "Bild veröffentlichen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['date']['0'] = "Erstellungsdatum";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['picture']['0'] ='Bild';
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['owner']['0'] = "Besitzer/Ersteller";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['name']['0'] = "Dateiname";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['addCustomThumb']['0'] = "Alternatives Vorschaubild";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['customThumb']['0'] = "Ein alternatives Vorschaubild auswählen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['title']['0'] = "Bildtitel";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['comment']['0'] = "Bildunterschrift";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['sorting']['0'] = "Sortierreihenfolge";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['filename']['0'] = "Dateiname";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['path']['0'] = "Pfad";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['socialMediaSRC']['0'] = "Alternativ zum Grossbild einen Film oder einen Sound von einer Social-Media-Plattform wiedergeben";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['socialMediaSRC']['1'] = "Geben Sie den vollen Pfad zum Medium an: https://www.youtube.com/embed/VOJyrQa_WR4?rel=0&wmode=transparent";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['localMediaSRC']['0'] = "Video oder Sound aus dem Contao-File-System wiedergeben";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cssID']['0'] = "CSS-ID/Klasse";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cssID']['1'] = "Hier können Sie dem Bild eine ID und beliebig viele Klassen zuordnen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['0'] = "Bildeinstellungen bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['edit']['1'] = "Bild mit ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['0'] = "Bild löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['delete']['1'] = "Bild mit ID %s löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['0'] = "Reihenfolge ändern";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['cut']['1'] = "Bild mit ID %s verschieben";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['0'] = "Unterhalb einfügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['paste']['1'] = "Unterhalb Bild mit ID %s einfügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['0'] = "Bild um 90° drehen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['imagerotate']['1'] = "Bild um 90° drehen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['fileupload']['0'] = "Bilder uploaden";
$GLOBALS['TL_LANG']['tl_gallery_creator_pictures']['fileupload']['1'] = "Bilder uploaden";
