<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_module.php 
 * 
 * Contao extension: gallery_creator 4.9.0
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2015 Marko Cupic
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['pagination_legend'] = "Pagination Einstellungen";
$GLOBALS['TL_LANG']['tl_module']['thumb_legend'] = "Thumbnail-Einstellungen";
$GLOBALS['TL_LANG']['tl_module']['image_legend'] = "Allgemeine Einstellungen";
$GLOBALS['TL_LANG']['tl_module']['excluded_albums_legend'] = "Ausgenommene Alben";
$GLOBALS['TL_LANG']['tl_module']['gc_rows']['0'] = "Vorschaubilder pro Reihe";
$GLOBALS['TL_LANG']['tl_module']['gc_rows']['1'] = "Wählen Sie die Anzahl Vorschaubilder pro Reihe aus. (0=So viele wie möglich)";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['0'] = "Galerietemplate";
$GLOBALS['TL_LANG']['tl_module']['gc_template']['1'] = "Hier können Sie das Galerietemplate auswählen.";
$GLOBALS['TL_LANG']['tl_module']['gc_activateThumbSlider']['0'] = "Ajax-Thumb-Slider aktivieren";
$GLOBALS['TL_LANG']['tl_module']['gc_activateThumbSlider']['1'] = "Ajax-Thumb-Slider bei mouseover in der Albenübersicht aktivieren?";
$GLOBALS['TL_LANG']['tl_module']['gc_AlbumsPerPage']['0'] = "Anzahl Alben pro Seite in der Albenübersicht";
$GLOBALS['TL_LANG']['tl_module']['gc_AlbumsPerPage']['1'] = "Die Anzahl an Alben pro Seite in der Albenübersicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_module']['gc_ThumbsPerPage']['0'] = "Anzahl Bilder pro Seite in der Detailansicht";
$GLOBALS['TL_LANG']['tl_module']['gc_ThumbsPerPage']['1'] = "Anzahl Bilder pro Seite in der Detailansicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_module']['gc_PaginationNumberOfLinks']['0'] = "Anzahl Links in der Pagination Navigation";
$GLOBALS['TL_LANG']['tl_module']['gc_PaginationNumberOfLinks']['1'] = "Legen Sie die Anzahl Links in der Pagination Navigation fest. Standardwert ist 7.";
$GLOBALS['TL_LANG']['tl_module']['gc_hierarchicalOutput']['0'] = "Alben im Frontend hierarchisch ausgeben";
$GLOBALS['TL_LANG']['tl_module']['gc_hierarchicalOutput']['1'] = "Sollen die Alben im Frontend hierarchisch anhand der Albumstruktur ausgegeben werden (Alben und Unteralben)?";
$GLOBALS['TL_LANG']['tl_module']['gc_size_detailview']['0'] = "Detailansicht: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_module']['gc_size_detailview']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_module']['gc_imagemargin_detailview']['0'] = "Detailansicht: Bildabstand";
$GLOBALS['TL_LANG']['tl_module']['gc_imagemargin_detailview']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_module']['gc_size_albumlisting']['0'] = "Albumauflistung: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_module']['gc_size_albumlisting']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_module']['gc_imagemargin_albumlisting']['0'] = "Albumauflistung: Bildabstand";
$GLOBALS['TL_LANG']['tl_module']['gc_imagemargin_albumlisting']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_module']['gc_fullsize']['0'] = "Großansicht/Neues Fenster";
$GLOBALS['TL_LANG']['tl_module']['gc_fullsize']['1'] = "Großansicht des Bildes in einer Lightbox bzw. den Link in einem neuem Browserfenster öffnen.";
$GLOBALS['TL_LANG']['tl_module']['gc_excludedAlbums']['0'] = "Ausgenommene Alben";
$GLOBALS['TL_LANG']['tl_module']['gc_excludedAlbums']['1'] = "Diese Alben nicht anzeigen.";
 
?>
